### ISSUE TITLE
Issue with singular matrix during backward pass

### ISSUE THREAD

**Issue by AvivNavon** [fagp/sinkhorn-rebasin#8]
Hi, thank you for this great work.
When trying to use the Sinkhorn code, I'm getting an error during backward pass:

```
grad_ab = torch.linalg.solve(K, t)
... The solver failed because the input matrix is singular.
```
Any suggestions on how to address this issue?

Thanks

**Comment by heitorrapela** [comment]
Hello,

Could you provide more information about how are you running the scripts and the env?

Best Regards,

**Comment by fagp** [comment]
> Hi, thank you for this great work. When trying to use the Sinkhorn code, I'm getting an error during backward pass:
> 
> ```
> grad_ab = torch.linalg.solve(K, t)
> ... The solver failed because the input matrix is singular.
> ```
> 
> Any suggestions on how to address this issue?
> 
> Thanks

Hi @AvivNavon,

Thank you for your interest in our work! It appears you're encountering an issue with a singular matrix when working with the Sinkhorn operator. This problem arises when attempting to compute the inverse of a matrix with a determinant equal to zero. To address this, we recommend the following solutions:

1. **Lower the Learning Rate:** High learning rates can cause your soft permutation matrix to have very high values, leading to entire rows and columns of zeros and resulting in a singular matrix. Try decreasing your learning rate to mitigate this issue. Additionally, consider experimenting with different optimizers to find the one that works best for your case.

2. **Explore `l` parameter:** Our [RebasinNet](https://github.com/fagp/sinkhorn-rebasin/blob/1c601d4060abcfb3653f2e8fd7cacb4aa63dc12e/rebasin/rebasinnet/symmnet.py#L176) has a non-documented parameter named `l`. Experiment with values between 0 and 1 for `l` as it may help you avoid the singular matrix problem.

Please don't hesitate to reach out via email (fidel-alejandro.guerrero-pena@etsmtl.ca) if you need further assistance with your specific scenario.

Best regards,
Fidel
